version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: edu3_user
      POSTGRES_PASSWORD: edu3_password
      POSTGRES_DB: edu3_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U edu3_user -d edu3_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
